---
title: "EDS212 Day4a"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

#Create matrices in r

```{r}
#create sequence of values
my_values <- seq(from=1, to=10, by=1)
my_values

#convert to matrix
my_matrix <- matrix(data= my_values,
                    nrow= 2,
                    ncol= 5,
                    byrow= TRUE)
class(my_matrix)
```

##Incorrectly declared matrix sizes
```{r}
matrix(data= my_values, nrow=3, ncol=4, byrow= TRUE)
```

##Let's do some math with matrices

```{r}
#scalar multiplication----
4*my_matrix


#Let's create a second matrix
my_values_2 <- seq( from=21, to=30, by=1)
my_matrix_2 <- matrix(data=my_values_2, nrow= 2, byrow=TRUE)
my_matrix_2

#add matrices
my_matrix + my_matrix_2
my_matrix_2 - my_matrix


```

##Making matrices for dot-product

```{r}
cats <- matrix(data=c(0,4,3,1), nrow=2, byrow= TRUE)
cats

dogs <- matrix(data=c(6,-3,0,2), nrow=2, byrow=TRUE)
dogs

cats %*% dogs

```


##Leslie matrix example

```{r}
#create the matrix
insect_leslie <- matrix(data= c(0,0,600,0.2,0,0,0,0.08,0), nrow=3, ncol=3, byrow=TRUE)
insect_leslie

#initial starting conditions----
insect_y0 <- c(12000, 700, 500)


#estimate population size at year 1 ----
insect_y1 <- insect_leslie %*% insect_y0

insect_y1
#year 2
insect_y2 <- insect_leslie %*% insect_y1
insect_y2
#year 3
insect_y3 <- insect_leslie %*% insect_y2
insect_y3
```


#Tree Leslie Matrix 

```{r}
tree_leslie <- matrix (data= c(0,0,5000, 0.1,0,0,0,0.06,0.95), nrow=3, ncol=3, byrow=TRUE)
tree_leslie

#data for year 1 of trees
tree_year0 <- c(5000,0,0)

tree_year1 <- tree_leslie %*% tree_year0
tree_year1
```


